import type { Metadata } from "next";
import "./globals.scss";
import LayoutPage from "@/components/layout/LayoutPage";
import { Frank_Ruhl_Libre, Inter, Abril_Fatface } from 'next/font/google';

const frankRuhlLibre = Frank_Ruhl_Libre({ subsets: ['latin'], weight: ['400', '700'] });
const inter = Inter({ subsets: ['latin'], weight: ['400', '500', '700'] });
const abrilFatface = Abril_Fatface({ subsets: ['latin'], weight: ['400'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={``}>
        <LayoutPage>{children}</LayoutPage>
         
      </body>
    </html>
  );
}
